<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>FocusLens.Agent</RootNamespace>
    <AssemblyName>FocusLensAgent</AssemblyName>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="System.IO" />
    <Using Include="System.Threading" />
    <Using Include="System.Threading.Tasks" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FocusLens.Core\FocusLens.Core.csproj" />
    <ProjectReference Include="..\FocusLens.Platform.Windows\FocusLens.Platform.Windows.csproj" />
  </ItemGroup>
</Project>
